FROM selenoid/dev_chrome:@@VERSION@@
COPY .profile /Profile1


COPY chromedriver /usr/bin/
COPY entrypoint.sh /

RUN chmod +x /usr/bin/chromedriver
USER selenium

EXPOSE 4444
ENTRYPOINT ["/entrypoint.sh"]
